//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YatzyApp.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YatzyApp.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Player.
        /// </summary>
        public static string AddPlayer {
            get {
                return ResourceManager.GetString("AddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Flush.
        /// </summary>
        public static string BigFlush {
            get {
                return ResourceManager.GetString("BigFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t have value .
        /// </summary>
        public static string CantHaveValue {
            get {
                return ResourceManager.GetString("CantHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Players.
        /// </summary>
        public static string ClearPlayers {
            get {
                return ResourceManager.GetString("ClearPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Points.
        /// </summary>
        public static string ClearPoints {
            get {
                return ResourceManager.GetString("ClearPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Numbers.
        /// </summary>
        public static string FourNumbers {
            get {
                return ResourceManager.GetString("FourNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full House.
        /// </summary>
        public static string FullHouse {
            get {
                return ResourceManager.GetString("FullHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Pair.
        /// </summary>
        public static string OnePair {
            get {
                return ResourceManager.GetString("OnePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name:.
        /// </summary>
        public static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point named.
        /// </summary>
        public static string PointNamed {
            get {
                return ResourceManager.GetString("PointNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        public static string SelectCulture {
            get {
                return ResourceManager.GetString("SelectCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Flush.
        /// </summary>
        public static string SmallFlush {
            get {
                return ResourceManager.GetString("SmallFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Numbers.
        /// </summary>
        public static string ThreeNumbers {
            get {
                return ResourceManager.GetString("ThreeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Pairs.
        /// </summary>
        public static string TwoPairs {
            get {
                return ResourceManager.GetString("TwoPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahtzee.
        /// </summary>
        public static string Yatzy {
            get {
                return ResourceManager.GetString("Yatzy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahtzee Calculator.
        /// </summary>
        public static string YatzyCalculator {
            get {
                return ResourceManager.GetString("YatzyCalculator", resourceCulture);
            }
        }
    }
}
